import GlobalProvider from "@/components/GlobalProvider"
import "./globals.css"
import type { Metadata } from "next"
import { Toaster } from "@/components/ui/toaster"
import { Inter as FontSans } from "next/font/google"
import { cn } from "@/lib/shadcnUtils"

export const fontSans = FontSans({
	subsets: ["latin"],
	variable: "--font-sans",
})

export const metadata: Metadata = {
	title: "Aplikasi Penyewaan Lapangan Badminton",
	description: "Generated by create next app",
}

const RootLayout = ({ children }: { children: React.ReactNode }) => {
	return (
		<GlobalProvider>
			<html lang="en">
				<body
					className={cn(
						"min-h-screen bg-background font-sans antialiased",
						fontSans.variable
					)}
				>
					{children}
					<Toaster />
				</body>
			</html>
		</GlobalProvider>
	)
}

export default RootLayout
